title : mili
tagline: Blog Tagline
author : mili
  name : Firstname Lastname
  email : miliwanderful@gmail.com
  github : username
  twitter : username
  feedburner : feedname

navigation :
  - archive.html        
  - tags.html
  - categories.html
  - projects.html
  - pages.html
  - about.md
  
