title : mili    
tagline: Blog Tagline
author :
  name : mili
  email : blah@email.test
  github : username
  twitter : username
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - projects.html
  - categories.html
  - pages.html
  - about.md

 
